# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hybridpredictmaize22',
                'doc_host': 'https://cjGO.github.io',
                'git_url': 'https://github.com/cjGO/hybridpredictmaize22',
                'lib_path': 'hybridpredictmaize22'},
  'syms': {'hybridpredictmaize22.core': {}}}
